import Head from "next/head";
import styles from "../styles/home.module.css";
import Header from "components/header";
import Link from 'next/link'

export default function home() {

  return (

    <div className={styles.container}>
      <Head>
        <title>Wifishare App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <div>
          <Link href="/uploader">

            uploader

          </Link>
        </div>
        <div>
          <Link href="/downloader">

            downloader

          </Link>
        </div>   </div></div>
  );}

  