import Head from "next/head";
import styles from "../styles/home.module.css";
import Header from "./header";
import Link from 'next/link'

const boxStyle = {
  width: 1200, height: 500, display: "flex", alignItems: "center",
  justifyContent: "center", backgroundColor: "#ebf6f4", color: "black",
  borderRadius: 10, margin: 10
}

const buttonStyle = {
  width: 188, height: 66,
  display: "flex", // 取消位置固定
  backgroundColor: "#f8cac0",
  justifyContent: "center", // 行居中
  alignItems: "center", // 列居中
  color:"#534d4c",
  fontSize: 30
}

const blankboxStyle = {
  width: 1200, height: 500, display: "flex", alignItems: "center",
  justifyContent: "center",
  borderRadius: 10, margin: 10
}

const blankStyle = {
  width:100, height: 100,
  backgroundColor:"#ebf6f4" 
}

function mouseOn(item) {
  item.style.backgroundColor = "#c6a199"
}

function mouseOut(item) {
  item.style.backgroundColor = "#f8cac0"
}

export default function home() {

  return (

    <div className={styles.container}>
      <Head>
        <title>Wifishare App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div>
        {/* uploader button */}
        <div class="box" style={boxStyle}>
          <Link href="/uploader">
            <p id="uploaderButton" style={buttonStyle} onMouseOver={
              async() =>{
                var button = document.getElementById("uploaderButton");
                mouseOn(button);

                button.onmouseout = function() {
                mouseOut(button);
                }
              }}>uploader</p>
          </Link>

            {/* downloader button */}
          <div style={blankStyle}></div>
          <Link href="/downloader">
           <p id="downloaderButton" style={buttonStyle} onMouseOver={
              async() =>{
                var button = document.getElementById("downloaderButton");
                mouseOn(button);

                button.onmouseout = function() {
                mouseOut(button);
                }
              }}>downloader</p>
          </Link>
        </div>

{/* 
        // brief introduction
        <div class="box" style={boxStyle}>1</div>
        
        // footer
        <div class="box" style={boxStyle}>2</div> 

*/}

        {/*
         <script type="text/js" src="./scripts/boxScrool.js"></script> 
         */}

      </div>
      
    </div>
  );}

  